### ISSUE TITLE
Playing of video with title containing question mark ("?") will fail

### ISSUE THREAD

**Issue by jose1711** [sparkylinux/sparky-tube#4]
To reproduce:
1. execute `sparky-tube`
2. set URL to https://www.youtube.com/watch?v=DR8aivPOkvw
3. choose `video:mkv` output format
4. set player to `ffplay`
5. enable 'Play after downloading'
6. confirm

Outcome:
- video is saved (question mark from the title is stripped)
- video is not played (`.. : No such file or directory`)

**Comment by pavroo** [comment]
0.1.28 moved to repos, give it a try.

**Comment by jose1711** [comment]
Thanks for the fix, works nicely.
